version: "3.3"
services:
  ahorcado_go:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8090:8090"
    networks:
      ahorcado:
    container_name: ahorcadogo

networks:
  ahorcado:
    driver: bridge