version: "3.9"
services:
  ahorcado:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks: 
      ahorcado:
    container_name: ahorcado
    environment:
      - MONGODB_NAME
      - MONGODB_PASSWORD

networks:
  ahorcado: 
    driver: bridge